#!/usr/bin/env python3
"""Turn battery/gui/index.html into a Pyodide page that needs no server.

The page is unchanged: every backend call goes through one `api(route, payload)`
function, which uses HTTP by default and `window.__HEMS_API__` when it exists.
This supplies that function by booting Pyodide in a web worker and exec'ing the
flattened bundle - the bootstrap admm/wasm/make_page.py already uses, loaded
from there and pointed at this page's bundle.

The output still FETCHES the bundle; tools/make_standalone.py inlines it (and
the kernels wheel, if built) afterwards.

Run:  battery/wasm/make_page.py        # -> battery/wasm/battery_page.html
"""

from __future__ import annotations

import argparse
import importlib.util
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parents[1]
GUI = ROOT / "battery" / "gui" / "index.html"

START = "/* HEMS-BOOT-START"
END = "/* HEMS-BOOT-END */"


def admm_boot() -> str:
    spec = importlib.util.spec_from_file_location("admm_make_page", ROOT / "admm" / "wasm" / "make_page.py")
    assert spec and spec.loader
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return str(mod.BOOT)


def retarget(boot: str) -> str:
    swaps = [
        ("admm_bundle.py", "battery_bundle.py"),
        ("generated by admm/wasm/make_page.py", "generated by battery/wasm/make_page.py (from admm/wasm/make_page.py)"),
    ]
    for old, new in swaps:
        if old not in boot:
            sys.exit(f"admm/wasm/make_page.py changed: {old!r} not found in its BOOT")
        boot = boot.replace(old, new)
    return boot


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--src", type=pathlib.Path, default=GUI)
    ap.add_argument("-o", "--out", type=pathlib.Path, default=HERE / "battery_page.html")
    args = ap.parse_args()

    html = args.src.read_text()
    a, b = html.find(START), html.find(END)
    if a < 0 or b < 0:
        sys.exit(f"no HEMS-BOOT markers in {args.src}")
    out = html[:a] + retarget(admm_boot()) + html[b + len(END):]

    for old, new in [
        ("Same solver as the tests run:", "Running in your browser, no server. Same solver as the tests run:"),
    ]:
        if old not in out:
            sys.exit(f"battery/gui/index.html changed: {old!r} not found")
        out = out.replace(old, new)

    args.out.write_text(out)
    print(f"wrote {args.out}  ({len(out):,} bytes)")


if __name__ == "__main__":
    main()
