#!/usr/bin/env python3
"""Flatten the single-battery page's Python into one module for Pyodide.

tools/make_standalone.py embeds a single module, and the page's Python is a
slice of the package: the battery DP, the policy layer that reads it, and the
page's backend. This concatenates those modules in dependency order into one
flat namespace, with every `home_energy_optimizer.*` or relative import removed.

The flattening itself is dw/wasm/make_bundle.py's, loaded rather than copied:
`strip_module` (imports removed or hoisted, nested ones left as a statement)
and `top_level_names` (a name defined twice fails the build).

Run:  battery/wasm/make_bundle.py [-o battery/wasm/battery_bundle.py]
"""

from __future__ import annotations

import argparse
import ast
import importlib.util
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parents[1]

# Dependency order: each module's package imports are already emitted.
ORDER = [
    "src/home_energy_optimizer/_kernels.py",
    "src/home_energy_optimizer/interp.py",
    "src/home_energy_optimizer/types.py",
    "src/home_energy_optimizer/meter.py",
    "src/home_energy_optimizer/dp_battery.py",      # the slow tier
    "src/home_energy_optimizer/policy.py",          # the fast tier
    "src/home_energy_optimizer/battery/webapi.py",  # the page's routes
]

HEADER = '''"""The single-battery page, flattened to one module for the browser.

GENERATED by battery/wasm/make_bundle.py -- do not edit. src/home_energy_optimizer/
is the source of truth; this is the same code with the module boundaries
removed so Pyodide can exec it in one go.

Modules included: {mods}
"""

from __future__ import annotations

'''

FOOTER = '''

# ---------------------------------------------------------------------------
# Browser entry point
# ---------------------------------------------------------------------------

def _api(route, payload_json):
    """Single call the page makes. Mirrors battery/gui/server.py's /api/<route>.

    JSON strings in and out, so nothing crosses the JS/Python boundary as a
    proxy - the page parses the result exactly as it parses an HTTP response.
    """
    import json as _json
    try:
        return _json.dumps(call(route, _json.loads(payload_json or "{}")))
    except Exception as exc:  # surfaced in the page, as the server does
        return _json.dumps({"error": str(exc)})
'''


def dw_builder():
    """dw/wasm/make_bundle.py as a module (it is a script, not a package)."""
    spec = importlib.util.spec_from_file_location("dw_make_bundle", ROOT / "dw" / "wasm" / "make_bundle.py")
    assert spec and spec.loader
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("-o", "--out", type=pathlib.Path, default=HERE / "battery_bundle.py")
    args = ap.parse_args()
    dw = dw_builder()

    parts, hoisted, seen = [], [], {}
    for rel in ORDER:
        body, imports, aliases = dw.strip_module(ROOT / rel, None)
        for name in dw.top_level_names(body):
            if name in seen and not name.startswith("_"):
                sys.exit(f"name collision: {name!r} in both {seen[name]} and {rel}")
            seen[name] = rel
        hoisted += [i for i in imports if i not in hoisted]
        tail = ("\n\n" + "\n".join(aliases)) if aliases else ""
        parts.append(f"# {'=' * 72}\n# {rel}\n# {'=' * 72}\n\n{body}{tail}\n")

    out = HEADER.format(mods=", ".join(ORDER)) + "\n".join(hoisted) + "\n\n\n" + "\n\n".join(parts) + FOOTER
    ast.parse(out)
    args.out.write_text(out)
    print(f"wrote {args.out}  ({len(out):,} bytes, {out.count(chr(10)):,} lines)")


if __name__ == "__main__":
    main()
