#!/usr/bin/env python3
"""Flatten the Dantzig-Wolfe app's Python into one module for Pyodide.

The counterpart of admm/wasm/make_bundle.py for dw/. The DW code imports across
the package - `home_energy_optimizer.*`, `.dw.*`, `.admm.*` - with absolute
imports, and the embedding tool (tools/make_standalone.py) takes a single
module. So:

* every `home_energy_optimizer.*` or relative import is removed, top level or
  nested; an alias (`linprog as np_linprog`) becomes an assignment;
* other imports are hoisted to the top and de-duplicated;
* from `admm.webapi` only `build_site` is taken - the rest of that module
  is the ADMM app's API and would collide with src/home_energy_optimizer/dw/webapi.py by name;
* any other top-level name collision fails the build rather than letting one
  module silently shadow another.

Run:  dw/wasm/make_bundle.py [-o dw/wasm/dw_bundle.py]
"""

from __future__ import annotations

import argparse
import ast
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parents[1]

# (path, only these top-level names or None for all), in dependency order
ORDER = [
    ("src/home_energy_optimizer/_kernels.py", None),
    ("src/home_energy_optimizer/interp.py", None),
    ("src/home_energy_optimizer/types.py", None),
    ("src/home_energy_optimizer/interface.py", None),          # the device query the coordinator sends participants
    ("src/home_energy_optimizer/profiles.py", None),
    ("src/home_energy_optimizer/meter.py", None),
    ("src/home_energy_optimizer/dp_battery.py", None),
    ("src/home_energy_optimizer/dp_thermal.py", None),
    ("src/home_energy_optimizer/coordinate.py", None),
    ("src/home_energy_optimizer/admm/battery_qp.py", None),             # the exact LP battery step
    ("src/home_energy_optimizer/admm/coordinator.py", None),            # ADMM (imports from coordinate)
    ("src/home_energy_optimizer/policy.py", None),       # the ADMM mode's value of a stored kWh
    ("src/home_energy_optimizer/admm/webapi.py", ["build_site"]),
    ("src/home_energy_optimizer/dw/lpsolver.py", None),
    ("src/home_energy_optimizer/dw/sensitivity.py", None),
    ("src/home_energy_optimizer/dw/coordinator.py", None),
    ("src/home_energy_optimizer/dw/attribution.py", None),              # who saves what (the page's ledger)
    ("src/home_energy_optimizer/dw/webapi.py", None),
]

HEADER = '''"""The Dantzig-Wolfe home-energy app, flattened to one module for the browser.

GENERATED by dw/wasm/make_bundle.py -- do not edit. src/home_energy_optimizer/
is the source of truth; this is the same code with the module boundaries
removed so Pyodide can exec it in one go.

Modules included: {mods}
"""

from __future__ import annotations

'''

FOOTER = '''

# ---------------------------------------------------------------------------
# Browser entry point
# ---------------------------------------------------------------------------

def _api(route, payload_json, progress=None):
    """Single call the page makes. Mirrors dw/gui/server.py's /api/<route>.

    JSON strings in and out, so nothing crosses the JS/Python boundary as a
    proxy - the page parses the result exactly as it parses an HTTP response.
    `progress(it, max_iter)`, if given, is the worker's callback: it posts
    each iteration to the page while the solve is still running.
    """
    import json as _json
    try:
        return _json.dumps(call(route, _json.loads(payload_json or "{}"), progress))
    except Exception as exc:  # surfaced in the UI, as the server does
        return _json.dumps({"error": str(exc)})
'''


def internal(node: ast.ImportFrom | ast.Import) -> bool:
    if isinstance(node, ast.ImportFrom):
        mod = node.module or ""
        return node.level > 0 or mod == "__future__" or mod.split(".")[0] == "home_energy_optimizer"
    return any(a.name.split(".")[0] == "home_energy_optimizer" for a in node.names)


def strip_module(path: pathlib.Path, only: list[str] | None):
    """Return (body, hoisted imports, alias assignments)."""
    src = path.read_text()
    tree = ast.parse(src)
    lines = src.splitlines()
    drop: set[int] = set()
    hoist: list[str] = []
    aliases: list[str] = []

    if ast.get_docstring(tree, clean=False) is not None:
        first = tree.body[0]
        drop.update(range(first.lineno - 1, first.end_lineno))

    for node in ast.walk(tree):
        if not isinstance(node, (ast.Import, ast.ImportFrom)):
            continue
        span = range(node.lineno - 1, node.end_lineno)
        if internal(node):
            renames = [f"{a.asname} = {a.name}" for a in node.names
                       if isinstance(node, ast.ImportFrom) and a.asname and a.asname != a.name]
            if node.col_offset:
                # nested: must leave a statement behind, or it could empty a block
                lines[node.lineno - 1] = " " * node.col_offset + ("; ".join(renames) or "pass")
                drop.update(range(node.lineno, node.end_lineno))
            else:
                drop.update(span)
                aliases.extend(renames)
            continue
        if node.col_offset:
            continue                      # nested third-party import: leave in place
        drop.update(span)
        hoist.append("\n".join(lines[i] for i in span))

    if only is not None:
        wanted = [n for n in tree.body if getattr(n, "name", None) in only]
        missing = set(only) - {n.name for n in wanted}
        if missing:
            sys.exit(f"{path}: not found: {sorted(missing)}")
        body = "\n\n\n".join("\n".join(lines[n.lineno - 1 - len(n.decorator_list): n.end_lineno])
                             for n in wanted)
        # keep only the imports those names use
        used = {x.id for n in wanted for x in ast.walk(n) if isinstance(x, ast.Name)}
        hoist = [h for h in hoist if any(name in used for name in _imported_names(h))]
        return body, hoist, aliases

    body = "\n".join(line for i, line in enumerate(lines) if i not in drop)
    return body.strip("\n"), hoist, aliases


def _imported_names(stmt: str) -> list[str]:
    node = ast.parse(stmt).body[0]
    return [(a.asname or a.name).split(".")[0] for a in node.names]


def top_level_names(src: str) -> set[str]:
    out = set()
    for node in ast.parse(src).body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            out.add(node.name)
        elif isinstance(node, ast.Assign):
            out.update(t.id for t in node.targets if isinstance(t, ast.Name))
        elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            out.add(node.target.id)
    return out


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("-o", "--out", type=pathlib.Path, default=HERE / "dw_bundle.py")
    args = ap.parse_args()

    parts, hoisted, seen = [], [], {}
    for rel, only in ORDER:
        path = ROOT / rel
        body, imports, aliases = strip_module(path, only)
        for name in top_level_names(body):
            if name in seen and not name.startswith("_"):
                sys.exit(f"name collision: {name!r} in both {seen[name]} and {rel}")
            seen[name] = rel
        hoisted += [i for i in imports if i not in hoisted]
        tail = ("\n\n" + "\n".join(aliases)) if aliases else ""
        label = rel + (f" (only {', '.join(only)})" if only else "")
        parts.append(f"# {'=' * 72}\n# {label}\n# {'=' * 72}\n\n{body}{tail}\n")

    mods = ", ".join(r for r, _ in ORDER)
    out = HEADER.format(mods=mods) + "\n".join(hoisted) + "\n\n\n" + "\n\n".join(parts) + FOOTER
    ast.parse(out)
    args.out.write_text(out)
    print(f"wrote {args.out}  ({len(out):,} bytes, {out.count(chr(10)):,} lines)")


if __name__ == "__main__":
    main()
