#!/usr/bin/env python3
"""Turn dw/gui/index.html into a Pyodide page that needs no server.

The UI is unchanged: every backend call goes through one `api(route, payload)`
function, which uses HTTP by default and `window.__HEMS_API__` when it exists.
This supplies that function by booting Pyodide in a web worker and exec'ing the
flattened bundle. The bootstrap is the one wasm/make_page.py already uses for
the ADMM app, retargeted: the DW bundle's name, this page's colour tokens, and
`solve()` as the entry point. The HiGHS option is dropped - scipy is not loaded
in the browser; the built-in solver is.

The output still FETCHES the bundle; wasm_batt_optimizer/make_standalone.py
inlines it (and the kernels wheel) afterwards.

Run:  dw/wasm/make_page.py            # -> dw/wasm/dw_page.html
"""

from __future__ import annotations

import argparse
import importlib.util
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parents[1]
GUI = ROOT / "dw" / "gui" / "index.html"

START = "/* HEMS-BOOT-START"
END = "/* HEMS-BOOT-END */"


def admm_boot() -> str:
    spec = importlib.util.spec_from_file_location("admm_make_page", ROOT / "wasm" / "make_page.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod.BOOT


def retarget(boot: str) -> str:
    swaps = [
        ("hemspolicy_bundle.py", "dw_bundle.py"),
        ("var(--red)", "var(--bad)"),
        ("var(--blue)", "var(--sel-ink)"),
        ("await boot();", "await solve();"),
        # the worker passes Python a callback that posts each DW iteration,
        # and the page hands it to the Solve button
        ('"    self.postMessage({id: m.id, result: api(m.route, m.payload)});",',
         '"    const prog = (it, n, a, b, c) => self.postMessage({id: m.id, progress: [it, n, a, b, c]});",\n'
         '  "    self.postMessage({id: m.id, result: api(m.route, m.payload, prog)});",'),
        ("      if(m.stage){ _status('Loading ' + m.stage + '\\u2026'); return; }",
         "      if(m.stage){ _status('Loading ' + m.stage + '\\u2026'); return; }\n"
         "      if(m.progress){ if(window.__HEMS_PROGRESS__) window.__HEMS_PROGRESS__(...m.progress); return; }"),
        ("generated by wasm/make_page.py", "generated by dw/wasm/make_page.py (from wasm/make_page.py)"),
        # a first solve that was paused leaves the button saying "Resume"
        ("    btn.disabled = false; btn.textContent = 'Solve';",
         "    btn.disabled = false; if(typeof PAUSED_ID === 'undefined' || PAUSED_ID === null) btn.textContent = 'Solve';"),
    ]
    for old, new in swaps:
        if old not in boot:
            sys.exit(f"wasm/make_page.py changed: {old!r} not found in its BOOT")
        boot = boot.replace(old, new)
    return boot


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--src", type=pathlib.Path, default=GUI)
    ap.add_argument("-o", "--out", type=pathlib.Path, default=HERE / "dw_page.html")
    args = ap.parse_args()

    html = args.src.read_text()
    a, b = html.find(START), html.find(END)
    if a < 0 or b < 0:
        sys.exit(f"no HEMS-BOOT markers in {args.src}")
    out = html[:a] + retarget(admm_boot()) + html[b + len(END):]

    row_start = out.find('<div class="row"><label title="Built-in: dw/lpsolver.py')
    row_end = out.find("</select></div>", row_start) + len("</select></div>")
    if row_start < 0 or row_end < len("</select></div>"):
        sys.exit("dw/gui/index.html changed: LP solver row not found")
    # one solver in the browser, so no choice to offer: keep the id the page reads
    out = out[:row_start] + '<input type="hidden" id="solver" value="numpy">' + out[row_end:]

    for old, new in [
        ('One LP at the meter; devices that aren\'t linear bid plans into it.',
         'One LP at the meter; devices that aren\'t linear bid plans into it. Runs entirely in your browser.'),
    ]:
        if old not in out:
            sys.exit(f"dw/gui/index.html changed: {old!r} not found")
        out = out.replace(old, new)

    args.out.write_text(out)
    print(f"wrote {args.out}  ({len(out):,} bytes)")


if __name__ == "__main__":
    main()
