#!/usr/bin/env python3
"""Flatten src/hemspolicy into one .py file for Pyodide.

`make_standalone.py` in wasm_batt_optimizer embeds a SINGLE Python module, but
hemspolicy is a package. Rather than ship a wheel or teach the browser about
packages, concatenate the modules the UI actually needs, in dependency order,
into one flat namespace.

Only the modules the testbed calls are included. `feeds` (urllib), `ha` and
`evcc` are deliberately left out: they talk to the network or to another
process, which a page in a browser tab cannot do and does not need.

Run:  wasm/make_bundle.py [-o wasm/hemspolicy_bundle.py]
"""

from __future__ import annotations

import argparse
import ast
import pathlib
import re
import sys

HERE = pathlib.Path(__file__).resolve().parent
SRC = HERE.parent / "src" / "hemspolicy"

# Dependency order, checked below rather than trusted: every intra-package
# import must already have been emitted by the time a module is appended.
ORDER = [
    "_kernels",
    "interp",
    "types",
    "profiles",
    "meter",
    "dp_battery",
    "dp_thermal",
    "policy",
    "coordinate",
    "battery_qp",
    "exchange",
    "webapi",
]

INTRA = re.compile(r"^from\s+\.\w*\s+import\s*\(?", re.M)
FUTURE = re.compile(r"^from __future__ import .*$", re.M)

HEADER = '''"""hemspolicy, flattened to one module for the browser.

GENERATED by wasm/make_bundle.py -- do not edit. The package under src/ is the
source of truth; this file is the same code with the module boundaries removed
so Pyodide can exec it in one go.

Modules included: {mods}
"""

from __future__ import annotations

'''

FOOTER = '''

# ---------------------------------------------------------------------------
# Browser entry point
# ---------------------------------------------------------------------------

def _api(route, payload_json):
    """Single call the page makes. Mirrors gui/server.py's /api/<route>.

    Takes and returns JSON strings rather than objects, so nothing has to be
    converted across the JS/Python boundary by Pyodide's proxies - the page
    parses the result itself, exactly as it parses an HTTP response.
    """
    import json as _json
    try:
        return _json.dumps(call(route, _json.loads(payload_json or "{}")))
    except Exception as exc:  # surfaced in the UI, same as the server does
        return _json.dumps({"error": str(exc)})
'''


def strip_module(path: pathlib.Path) -> tuple[str, list[str]]:
    """Return (body without imports, the import lines worth hoisting).

    Walks the whole tree, not just the top level: a relative import inside a
    function body is still a relative import, and in a flat bundle there is no
    package for it to resolve against. policy.py has one (a deferred import of
    dp_battery._feasible_actions to dodge a cycle), and it only surfaced at
    call time - so this walks everything rather than trusting placement.
    """
    src = path.read_text()
    tree = ast.parse(src)
    lines = src.splitlines()
    drop: set[int] = set()
    hoist: list[str] = []

    # The module docstring. Once flattened it is no longer the first statement
    # of anything, so make_standalone's obfuscator - which only collapses a
    # docstring in first position - leaves it in the shipped payload verbatim.
    # It is also the most descriptive prose in the file, i.e. exactly what
    # obfuscation is for.
    doc = ast.get_docstring(tree, clean=False)
    if doc is not None and tree.body:
        first = tree.body[0]
        drop.update(range(first.lineno - 1, first.end_lineno))

    for node in ast.walk(tree):
        if not isinstance(node, (ast.Import, ast.ImportFrom)):
            continue
        span = range(node.lineno - 1, node.end_lineno)
        # Intra-package and __future__ imports vanish; everything else is
        # hoisted to the top of the bundle and de-duplicated there.
        if isinstance(node, ast.ImportFrom) and (node.level > 0 or node.module == "__future__"):
            # A nested one must leave a statement behind, or it would empty an
            # indented block. Rebind the flat name to what the import promised.
            if node.col_offset:
                pad = " " * node.col_offset
                lines[node.lineno - 1] = pad + "; ".join(
                    f"{a.asname or a.name} = {a.name}" for a in node.names
                )
                drop.update(range(node.lineno, node.end_lineno))
            else:
                drop.update(span)
            continue
        # A non-relative import that is INDENTED stays exactly where it is:
        # `_kernels` guards `import dp_kernels` in a try/except, and hoisting
        # it left an empty try block.
        if node.col_offset:
            continue
        drop.update(span)
        hoist.append("\n".join(lines[i] for i in span))

    body = "\n".join(l for i, l in enumerate(lines) if i not in drop)
    return body.strip("\n"), hoist


def top_level_names(src: str) -> set[str]:
    out = set()
    for node in ast.parse(src).body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            out.add(node.name)
        elif isinstance(node, ast.Assign):
            for t in node.targets:
                if isinstance(t, ast.Name):
                    out.add(t.id)
        elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            out.add(node.target.id)
    return out


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("-o", "--out", type=pathlib.Path,
                    default=HERE / "hemspolicy_bundle.py")
    args = ap.parse_args()

    parts: list[str] = []
    hoisted: list[str] = []
    seen: dict[str, str] = {}   # top-level name -> module that defined it

    for mod in ORDER:
        path = SRC / f"{mod}.py"
        if not path.exists():
            sys.exit(f"missing module: {path}")
        body, imports = strip_module(path)

        # A flat namespace means two modules cannot define the same name. This
        # holds today; fail loudly rather than silently shadow one later.
        for name in top_level_names(body):
            if name in seen and not name.startswith("_"):
                sys.exit(f"name collision: {name!r} in both {seen[name]} and {mod}")
            seen[name] = mod

        for imp in imports:
            if imp not in hoisted:
                hoisted.append(imp)
        parts.append(f"# {'=' * 72}\n# {mod}.py\n# {'=' * 72}\n\n{body}\n")

    out = (HEADER.format(mods=", ".join(ORDER))
           + "\n".join(hoisted) + "\n\n\n"
           + "\n\n".join(parts)
           + FOOTER)

    # The bundle must at least parse and import cleanly before it is shipped.
    ast.parse(out)
    args.out.write_text(out)
    print(f"wrote {args.out}  ({len(out):,} bytes, {out.count(chr(10)):,} lines)")


if __name__ == "__main__":
    main()
