#!/usr/bin/env python3
"""Turn gui/index.html into a Pyodide page that needs no server.

The UI is unchanged. gui/index.html routes every backend call through one
`api(route, payload)` function which uses HTTP by default and
`window.__HEMS_API__` when it exists; this script supplies that function by
booting Pyodide, loading numpy, and exec'ing the flattened bundle.

The output still FETCHES the bundle at runtime, which is what
wasm_batt_optimizer/make_standalone.py needs in order to find its insertion
point. Run that afterwards to inline the payload into a single file.

Run:  wasm/make_page.py            # -> wasm/hems_policy.html
"""

from __future__ import annotations

import argparse
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
GUI = HERE.parent / "gui" / "index.html"

START = "/* HEMS-BOOT-START"
END = "/* HEMS-BOOT-END */"

# The fetch line must match make_standalone.py's FETCH_RE exactly:
#   ^[ \t]*const NAME = await (await fetch(...)).text();$
BOOT = '''/* HEMS-BOOT-START -- generated by wasm/make_page.py. Replaces the direct
   boot() call with a Pyodide bootstrap and installs window.__HEMS_API__, so
   api() stops going over HTTP. Nothing above this line differs from the
   served page.

   Pyodide runs in a WEB WORKER, not on this thread. A solve is seconds of
   straight-line numpy, and on the main thread that is seconds of frozen tab -
   moving a slider produced "page not responding". In a worker the UI keeps
   painting and the controls keep working while the solve runs. */

const PYODIDE = "https://cdn.jsdelivr.net/pyodide/v0.26.2/full/";

/* The worker, as source. Built as an array rather than a template literal so
   that neither backticks nor ${} collide with the outer page. It uses the
   classic (importScripts) Pyodide build so this is a plain worker rather than
   a module worker. */
const WORKER_SRC = [
  "self.importScripts('" + PYODIDE + "pyodide.js');",
  "let py = null, api = null;",
  "self.onmessage = async (e) => {",
  "  const m = e.data;",
  "  try {",
  "    if (m.cmd === 'boot') {",
  "      self.postMessage({id: m.id, stage: 'the Python runtime'});",
  "      py = await self.loadPyodide({indexURL: '" + PYODIDE + "'});",
  "      self.postMessage({id: m.id, stage: 'numpy'});",
  "      await py.loadPackage('numpy');",
  "      self.postMessage({id: m.id, ready: true});",
  "      return;",
  "    }",
  "    if (m.cmd === 'loadPackage') {",
  "      await py.loadPackage(m.pkg);",
  "      self.postMessage({id: m.id, ready: true});",
  "      return;",
  "    }",
  "    if (m.cmd === 'run') {",
  "      await py.runPythonAsync(m.src);",
  "      self.postMessage({id: m.id, ready: true});",
  "      return;",
  "    }",
  "    if (m.cmd === 'ready') {",
  "      api = py.globals.get('_api');",
  "      self.postMessage({id: m.id, ready: true});",
  "      return;",
  "    }",
  "    self.postMessage({id: m.id, result: api(m.route, m.payload)});",
  "  } catch (err) {",
  "    self.postMessage({id: m.id, error: String((err && err.message) || err)});",
  "  }",
  "};",
].join("\\n");

function _status(msg, bad){
  const e = $('#err');
  if(!msg){ e.style.display = 'none'; return; }
  e.style.background   = bad ? 'rgba(252,165,165,.12)' : 'rgba(96,165,250,.12)';
  e.style.borderColor  = bad ? 'var(--red)'  : 'var(--blue)';
  e.style.color        = bad ? 'var(--red)'  : 'var(--blue)';
  e.textContent = msg;
  e.style.display = 'block';
}

(async () => {
  const btn = $('#solve');
  btn.disabled = true; btn.textContent = 'Loading\\u2026';
  try{
    const worker = new Worker(URL.createObjectURL(
      new Blob([WORKER_SRC], {type: 'text/javascript'})));

    let seq = 0;
    const pending = new Map();
    worker.onmessage = (e) => {
      const m = e.data;
      if(m.stage){ _status('Loading ' + m.stage + '\\u2026'); return; }
      const p = pending.get(m.id);
      if(!p) return;
      pending.delete(m.id);
      if(m.error) p({error: m.error});
      else if(m.ready) p(true);
      else p(JSON.parse(m.result));
    };
    worker.onerror = (e) => _status('Solver worker failed: ' + e.message, true);

    const send = (msg) => new Promise(resolve => {
      const id = ++seq;
      pending.set(id, resolve);
      worker.postMessage(Object.assign({id}, msg));
    });

    await send({cmd: 'boot'});

    /* make_standalone.py splices its payload over the fetch line below, and
       the wheel half of that payload is written against a main-thread
       `pyodide` object. Pyodide is in the worker here, so this shim gives that
       generated code the two methods it uses and forwards them. It also means
       the tool needs no knowledge of the worker. */
    const pyodide = {
      loadPackage: (pkg) => send({cmd: 'loadPackage', pkg}),
      runPythonAsync: (src) => send({cmd: 'run', src}),
    };
    void pyodide;

    _status('Loading the solver\u2026');
    const code = await (await fetch(`hemspolicy_bundle.py?t=${Date.now()}`)).text();

    await send({cmd: 'run', src: code});
    await send({cmd: 'ready'});
    window.__HEMS_API__ = (route, payload) =>
      send({route, payload: JSON.stringify(payload || {})});

    _status('');
    await boot();
  }catch(e){
    _status('Could not start the in-browser solver: ' + e.message, true);
  }finally{
    btn.disabled = false; btn.textContent = 'Solve';
  }
})();
/* HEMS-BOOT-END */'''


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--src", type=pathlib.Path, default=GUI)
    ap.add_argument("-o", "--out", type=pathlib.Path, default=HERE / "hems_policy.html")
    args = ap.parse_args()

    html = args.src.read_text()
    a, b = html.find(START), html.find(END)
    if a < 0 or b < 0:
        sys.exit(f"no HEMS-BOOT markers in {args.src}; the page cannot be retargeted")

    out = html[:a] + BOOT + html[b + len(END):]
    out = out.replace(
        "<span class=\"sub\">same code the tests run · no Pyodide, no second implementation</span>",
        "<span class=\"sub\">same code the tests run · in your browser, no server</span>")
    args.out.write_text(out)
    print(f"wrote {args.out}  ({len(out):,} bytes)")
    print("serve it (file:// blocks ES module imports):")
    print(f"    python3 -m http.server -d {args.out.parent} 8765")


if __name__ == "__main__":
    main()
