#!/usr/bin/env python3
"""
make_standalone.py — build a self-contained Pyodide HTML page.

Takes an HTML page that fetches its Python at runtime, plus that Python file,
and emits a single HTML file with two embedded payloads:

  _whl    base64 of a Cython->WASM wheel (compiled DP kernels)
  _pysrc  zlib+base64 of the obfuscated Python UI/coordination code

The obfuscation (comments and docstrings stripped, most functions renamed,
the whole payload zlib-compressed) is kept as a proof of concept of shipping a
solver in a page without its source: the source of this repository is public.

In this repository the two page builds call it - admm/wasm/build.sh and
dw/wasm/build.sh - with the kernel wheel from wasm/build/dist (built by
wasm/build_wheel.sh) or --no-wheel. Directly:

    # reuse an already-built wheel
    tools/make_standalone.py --wheel "wasm/build/dist/*wasm32.whl" \
        --html page.html --py bundle.py --out page_standalone.html

    # pure-Python page, no compiled kernels
    tools/make_standalone.py --no-wheel --html page.html --py bundle.py --out page_standalone.html

Then serve it -- file:// will not work, the browser blocks ES module imports:

    python3 -m http.server 8765
"""

from __future__ import annotations

import argparse
import ast
import base64
import glob
import io
import keyword
import pathlib
import random
import re
import shutil
import string
import subprocess
import sys
import tokenize
import zipfile
import zlib

HERE = pathlib.Path(__file__).resolve().parent
BUILD_DIR = HERE.parent / "wasm" / "build"      # the kernels' Cython sources and dist/
IMAGE = "pyodide-builder:0.26.2"

BEGIN = "// --- BEGIN EMBEDDED PAYLOAD (generated by make_standalone.py) ---"
END = "// --- END EMBEDDED PAYLOAD ---"

# Matches the runtime loader in the non-standalone pages, e.g.
#   const code = await (await fetch(`multi_device_utils.py?t=${Date.now()}`)).text();
FETCH_RE = re.compile(
    r"^[ \t]*const\s+(\w+)\s*=\s*await\s*\(await\s*fetch\([^\n]*?\)\)\.text\(\);[ \t]*$",
    re.M,
)

# Names that must survive obfuscation regardless of what the HTML references.
ALWAYS_KEEP = {"main", "setup", "__init__", "__main__"}


# ----------------------------------------------------------------------------
# wheel
# ----------------------------------------------------------------------------

def build_wheel(rebuild_image: bool = False) -> pathlib.Path:
    """Cross-compile build/*.pyx to a Pyodide wasm32 wheel inside Docker."""
    if not shutil.which("docker"):
        sys.exit("docker not found; build the wheel elsewhere and pass --wheel")

    have = subprocess.run(["docker", "image", "inspect", IMAGE],
                          capture_output=True).returncode == 0
    if rebuild_image or not have:
        print(f"[wheel] building image {IMAGE} (slow the first time)")
        subprocess.run(["docker", "build", "-t", IMAGE, "."],
                       cwd=BUILD_DIR, check=True)

    # BUILD_DIR is bind-mounted, so setuptools intermediates survive between
    # runs and it will happily relink a stale .o -- silently ignoring changed
    # compiler flags or an edited .pyx.
    for stale in ("dist", "build", "_skbuild"):
        shutil.rmtree(BUILD_DIR / stale, ignore_errors=True)
    for pat in ("*.c", "*.so", "*.egg-info", ".pyodide-xbuildenv*"):
        for p in BUILD_DIR.glob(pat):
            shutil.rmtree(p) if p.is_dir() else p.unlink()

    print("[wheel] cross-compiling with pyodide build")
    subprocess.run([
        "docker", "run", "--rm", "-v", f"{BUILD_DIR}:/src", IMAGE,
        "bash", "-lc",
        "source /opt/emsdk/emsdk_env.sh >/dev/null 2>&1; "
        "cd /src && pyodide build --exports pyinit",
    ], check=True)

    found = sorted((BUILD_DIR / "dist").glob("*pyodide*wasm32.whl"))
    if not found:
        sys.exit(f"no pyodide wasm32 wheel produced in {BUILD_DIR / 'dist'}")
    return found[0]


def wasm_opt(whl: pathlib.Path) -> pathlib.Path:
    """Run binaryen's wasm-opt -Oz over the .so inside the wheel, in place.

    Off by default: measured gain on these kernels is 1.1% of the wheel (621B),
    because the .so is dominated by CPython interface glue that -Oz cannot
    touch. Kept because it is correct and costs one flag if the kernels grow.
    """
    binary = "/opt/emsdk/upstream/bin/wasm-opt"
    script = f'''
set -e
cd /tmp && rm -rf wopt && mkdir wopt && cd wopt
python - <<'PY'
import zipfile
zipfile.ZipFile("/src/dist/{whl.name}").extractall(".")
PY
for f in *.so; do
  {binary} -Oz --enable-bulk-memory --enable-nontrapping-float-to-int "$f" -o "$f.opt"
  mv "$f.opt" "$f"
done
python - <<'PY'
import base64, csv, hashlib, pathlib, zipfile

root = pathlib.Path(".")
rec = next(root.glob("*.dist-info/RECORD"))
rows = list(csv.reader(rec.read_text().splitlines()))

# wasm-opt changed the .so, so its RECORD hash and size are now stale.
for row in rows:
    if not row or not row[0].endswith(".so"):
        continue
    data = (root / row[0]).read_bytes()
    digest = base64.urlsafe_b64encode(hashlib.sha256(data).digest()).rstrip(b"=")
    row[1] = "sha256=" + digest.decode()
    row[2] = str(len(data))

with rec.open("w", newline="") as fh:
    csv.writer(fh).writerows(rows)

out = pathlib.Path("/src/dist/{whl.name}")
with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as z:
    for p in sorted(root.rglob("*")):
        if p.is_file():
            z.write(p, p.relative_to(root).as_posix())
PY
'''
    before = whl.stat().st_size
    subprocess.run(["docker", "run", "--rm", "-v", f"{BUILD_DIR}:/src", IMAGE,
                    "bash", "-lc", script], check=True)
    after = whl.stat().st_size
    print(f"[wasm-opt] wheel {before:,}B -> {after:,}B "
          f"({100 * (before - after) / before:.1f}% smaller)")
    return whl


def describe_wheel(path: pathlib.Path) -> str:
    """Sanity-check the wheel and return a one-line summary for the HTML."""
    raw = path.read_bytes()
    with zipfile.ZipFile(io.BytesIO(raw)) as z:
        sos = [n for n in z.namelist() if n.endswith(".so")]
        if not sos:
            sys.exit(f"{path.name} contains no .so — not a compiled wheel")
        so = z.getinfo(sos[0])
        if z.read(sos[0])[:4] != b"\0asm":
            sys.exit(f"{sos[0]} is not a WebAssembly binary — wrong build host?")
    # micropip parses the filename; it must carry version + platform tags.
    if len(path.stem.split("-")) < 5:
        sys.exit(f"{path.name}: micropip needs the full "
                 f"name-version-pytag-abitag-plattag.whl form")
    return f"Compiled WASM kernels (Cython->C->WebAssembly, {so.file_size // 1024}KB .so)"


# ----------------------------------------------------------------------------
# python obfuscation
# ----------------------------------------------------------------------------

TEMPLATE_RE = re.compile(r"`(?:\\.|[^`\\])*`", re.S)
GLOBALS_GET_RE = re.compile(r"""globals\.get\(\s*['"](\w+)['"]""")


def _template_spans(html: str) -> list[tuple[int, int]]:
    """Character spans of JS template literals -- where Python source is embedded.

    Every call from the page into Python lives in one of these (runPythonAsync
    blocks, the create_proxy setup string), so they are the only regions where
    renaming a Python function must be mirrored.
    """
    return [m.span() for m in TEMPLATE_RE.finditer(html)]


def _reserved_from_html(html: str, spans: list[tuple[int, int]]) -> set[str]:
    """Names the page uses that must not be renamed.

    Two sources: identifiers appearing *outside* template literals (those are
    JS-side -- a variable, a function, an element id -- and renaming the Python
    would desynchronise them), and names pulled across with
    pyodide.globals.get("..."), which is a plain string the rename pass
    cannot see.
    """
    blanked = list(html)
    for a, b in spans:
        blanked[a:b] = " " * (b - a)
    outside = "".join(blanked)
    return (set(re.findall(r"[A-Za-z_]\w*", outside))
            | set(GLOBALS_GET_RE.findall(html)))


def rename_in_html(html: str, mapping: dict[str, str],
                   spans: list[tuple[int, int]]) -> tuple[str, int]:
    """Apply the rename map inside template literals only."""
    if not mapping:
        return html, 0
    pat = re.compile(r"\b(" + "|".join(re.escape(k) for k in mapping) + r")\b")
    hits = 0
    out = html
    for a, b in reversed(spans):                       # back-to-front: spans hold
        chunk, n = pat.subn(lambda m: mapping[m.group(1)], out[a:b])
        hits += n
        out = out[:a] + chunk + out[b:]
    return out, hits


def _rename_map(names: list[str], seed: int) -> dict[str, str]:
    rng = random.Random(seed)
    used: set[str] = set()
    out: dict[str, str] = {}
    for name in sorted(names):
        while True:
            cand = "_" + "".join(rng.choice(string.ascii_lowercase) for _ in range(5))
            if cand not in used:
                break
        used.add(cand)
        out[name] = cand
    return out


def obfuscate(src: str, reserved: set[str], seed: int,
              rename: bool = True) -> tuple[str, dict[str, str]]:
    """Strip comments, collapse docstrings, rename non-reserved functions.

    Edits are collected as (start, end, replacement) character spans and applied
    back-to-front, so the source is never re-parsed mid-transform.
    """
    lines = src.splitlines(keepends=True)
    offsets = [0]
    for ln in lines:
        offsets.append(offsets[-1] + len(ln))

    def pos(row: int, col: int) -> int:
        """Character offset of a tokenize (row, col)."""
        return offsets[row - 1] + col

    def ast_pos(row: int, col: int) -> int:
        """Character offset of an ast (row, col_offset).

        ast reports col_offset in UTF-8 *bytes*; tokenize and str slicing count
        characters. They agree only on pure-ASCII lines, so a docstring holding
        one em dash would overrun its span and swallow the start of the next
        statement.
        """
        return offsets[row - 1] + len(lines[row - 1].encode()[:col].decode())

    tree = ast.parse(src)

    # --- pick rename targets -------------------------------------------------
    defs = [n.name for n in ast.walk(tree)
            if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef))]
    targets = sorted({d for d in defs
                      if d not in reserved
                      and d not in ALWAYS_KEEP
                      and not d.startswith("__")
                      and not keyword.iskeyword(d)})
    mapping = _rename_map(targets, seed) if rename else {}

    edits: list[tuple[int, int, str]] = []

    # --- docstrings ----------------------------------------------------------
    for node in ast.walk(tree):
        if not isinstance(node, (ast.Module, ast.FunctionDef,
                                 ast.AsyncFunctionDef, ast.ClassDef)):
            continue
        if not node.body:
            continue
        first = node.body[0]
        if (isinstance(first, ast.Expr) and isinstance(first.value, ast.Constant)
                and isinstance(first.value.value, str)):
            edits.append((ast_pos(first.lineno, first.col_offset),
                          ast_pos(first.end_lineno, first.end_col_offset),
                          '""""""'))

    # --- comments and identifier tokens --------------------------------------
    toks = list(tokenize.generate_tokens(io.StringIO(src).readline))
    for i, tok in enumerate(toks):
        if tok.type == tokenize.COMMENT:
            row = tok.start[0]
            before = src[offsets[row - 1]:pos(*tok.start)]
            if before.strip() == "":
                # Whole-line comment: drop the line and its newline. Recorded as
                # a span, not a line number, because earlier edits (docstring
                # collapse) change how many lines the file has.
                edits.append((offsets[row - 1], offsets[row], ""))
            else:
                edits.append((pos(*tok.start), pos(*tok.end), ""))  # trailing
            continue

        if tok.type != tokenize.NAME or tok.string not in mapping:
            continue

        # obj.name -> attribute access, not our function
        prev = next((t for t in reversed(toks[:i])
                     if t.type not in (tokenize.NL, tokenize.NEWLINE,
                                       tokenize.INDENT, tokenize.DEDENT,
                                       tokenize.COMMENT)), None)
        if prev is not None and prev.type == tokenize.OP and prev.string == ".":
            continue

        # f(name=...) -> keyword argument, not our function
        nxt = next((t for t in toks[i + 1:]
                    if t.type not in (tokenize.NL, tokenize.NEWLINE,
                                      tokenize.COMMENT)), None)
        if (nxt is not None and nxt.type == tokenize.OP and nxt.string == "="
                and prev is not None and prev.type == tokenize.OP
                and prev.string in "(,"):
            continue

        edits.append((pos(*tok.start), pos(*tok.end), mapping[tok.string]))

    # --- apply ---------------------------------------------------------------
    out = src
    for start, end, repl in sorted(edits, key=lambda e: -e[0]):
        out = out[:start] + repl + out[end:]

    # A renamed name surviving in the output means it was referenced from a
    # string -- getattr(), a dispatch table -- which the token pass cannot see.
    for old in mapping:
        if re.search(rf"\b{re.escape(old)}\b", out):
            print(f"[warn] '{old}' still appears after renaming (string "
                  f"reference?); add --keep {old} if the page breaks",
                  file=sys.stderr)

    compile(out, "<obfuscated>", "exec")  # must still parse
    return out, mapping


# ----------------------------------------------------------------------------
# html assembly
# ----------------------------------------------------------------------------

def payload_block(indent: str, py_b64: str, var: str,
                  whl_b64: str | None, whl_name: str | None,
                  whl_note: str | None) -> str:
    L: list[str] = [BEGIN]
    if whl_b64:
        L += [
            f"// {whl_note}",
            f'const _whl = "{whl_b64}";',
        ]
    L += [
        "// Obfuscated Python UI/coordination code (zlib+base64)",
        f'const _pysrc = "{py_b64}";',
        "",
    ]
    if whl_b64:
        L += [
            "// Write the wheel into Pyodide's Emscripten FS and install from there.",
            "// emfs:// not file:// -- file:// is intercepted by the browser and",
            "// routed to the HTTP server, which 404s.",
            'await pyodide.loadPackage("micropip");',
            "await pyodide.runPythonAsync(`",
            "import base64, os",
            'os.makedirs("/tmp/wheels", exist_ok=True)',
            f'_whl_name = "{whl_name}"',
            'with open(f"/tmp/wheels/{_whl_name}", "wb") as f:',
            '    f.write(base64.b64decode("${_whl}"))',
            "import micropip",
            'await micropip.install(f"emfs:///tmp/wheels/{_whl_name}")',
            "`);",
            "",
        ]
    L += [
        f'const {var} = `import base64 as _b, zlib as _z; '
        f'exec(_z.decompress(_b.b64decode("${{_pysrc}}")))`;',
        END,
    ]
    # Only indent JS lines; the runPythonAsync template literal is Python
    # source where added leading whitespace would be a syntax error.
    inside_py = False
    out = []
    for line in L:
        if line.endswith("runPythonAsync(`"):
            out.append(indent + line)
            inside_py = True
            continue
        if inside_py:
            out.append(line)
            if line == "`);":
                inside_py = False
            continue
        out.append(indent + line if line else "")
    return "\n".join(out)


def splice(html: str, block: str) -> str:
    if BEGIN in html and END in html:
        return re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), lambda _: block,
                      html, flags=re.S)
    m = FETCH_RE.search(html)
    if not m:
        sys.exit("could not find an insertion point: no BEGIN/END markers and "
                 "no `const X = await (await fetch(...)).text();` loader line")
    return html[:m.start()] + block + html[m.end():]


def loader_var(html: str) -> str:
    if BEGIN in html:
        m = re.search(r"const (\w+) = `import base64 as _b", html)
        if m:
            return m.group(1)
    m = FETCH_RE.search(html)
    return m.group(1) if m else "code"


# ----------------------------------------------------------------------------

def main() -> None:
    ap = argparse.ArgumentParser(
        description="Build a self-contained Pyodide HTML page "
                    "(wasm wheel + obfuscated Python embedded).")
    ap.add_argument("--html", required=True, type=pathlib.Path,
                    help="source page (fetches the .py) or an existing standalone")
    ap.add_argument("--py", required=True, type=pathlib.Path,
                    help="Python module to obfuscate and embed")
    ap.add_argument("--out", required=True, type=pathlib.Path)

    g = ap.add_mutually_exclusive_group()
    g.add_argument("--wheel", type=str, help="prebuilt wasm32 wheel (glob ok)")
    g.add_argument("--build-wheel", action="store_true",
                   help="cross-compile build/*.pyx via Docker first")
    g.add_argument("--no-wheel", action="store_true",
                   help="pure-Python page, embed only the Python payload")

    ap.add_argument("--rebuild-image", action="store_true",
                    help="force a rebuild of the Docker builder image")
    ap.add_argument("--wasm-opt", action="store_true",
                    help="run binaryen wasm-opt -Oz over a freshly built wheel "
                         "(measured: ~1.1%%, 621B — rarely worth the extra pass)")
    ap.add_argument("--keep", action="append", default=[], metavar="NAME",
                    help="extra function name to leave unrenamed (repeatable)")
    ap.add_argument("--no-rename", action="store_true",
                    help="strip comments/docstrings but keep function names")
    ap.add_argument("--seed", type=int, default=0,
                    help="RNG seed for renaming; same seed = same output")
    args = ap.parse_args()

    html = args.html.read_text()
    py_src = args.py.read_text()

    # --- wheel ---------------------------------------------------------------
    whl_b64 = whl_name = whl_note = None
    if not args.no_wheel:
        if args.build_wheel:
            whl_path = build_wheel(args.rebuild_image)
            if args.wasm_opt:
                whl_path = wasm_opt(whl_path)
        elif args.wheel:
            hits = sorted(glob.glob(args.wheel))
            if not hits:
                sys.exit(f"no wheel matched {args.wheel!r}")
            whl_path = pathlib.Path(hits[0])
        else:
            hits = sorted(BUILD_DIR.glob("dist/*wasm32.whl"))
            if not hits:
                sys.exit("no wheel found in build/dist; pass --wheel, "
                         "--build-wheel, or --no-wheel")
            whl_path = hits[0]
        whl_note = describe_wheel(whl_path)
        whl_name = whl_path.name
        whl_b64 = base64.b64encode(whl_path.read_bytes()).decode()
        print(f"[wheel] {whl_name}  "
              f"{whl_path.stat().st_size:,}B -> {len(whl_b64):,} b64 chars")

    # --- python --------------------------------------------------------------
    spans = _template_spans(html)
    reserved = _reserved_from_html(html, spans) | set(args.keep)
    obf, mapping = obfuscate(py_src, reserved, args.seed,
                             rename=not args.no_rename)
    packed = zlib.compress(obf.encode(), 9)
    py_b64 = base64.b64encode(packed).decode()
    print(f"[py]    {len(py_src):,} chars -> {len(obf):,} obfuscated "
          f"-> {len(packed):,} zlib -> {len(py_b64):,} b64 chars "
          f"({len(mapping)} functions renamed)")

    # --- assemble ------------------------------------------------------------
    anchor = FETCH_RE.search(html)
    indent = (re.match(r"[ \t]*", anchor.group(0)).group(0)
              if anchor else "  ")
    # Mirror the renames into the page's embedded Python before splicing, so
    # runPythonAsync call sites still resolve.
    html, hits = rename_in_html(html, mapping, spans)
    print(f"[html]  {hits} call site(s) rewritten in "
          f"{len(spans)} template literal(s)")
    block = payload_block(indent, py_b64, loader_var(html),
                          whl_b64, whl_name, whl_note)
    args.out.write_text(splice(html, block))
    print(f"[out]   {args.out}  {args.out.stat().st_size:,} bytes")
    print("        serve over HTTP (file:// blocks the ES module import):")
    print(f"        python3 -m http.server 8765  ->  "
          f"http://localhost:8765/{args.out.name}")


if __name__ == "__main__":
    main()
